# Generated by Django 5.1.1 on 2024-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('Makanan/Minuman', 'Makanan/Minuman'), ('Komunikasi', 'Komunikasi'), ('Transportasi', 'Transportasi'), ('Pendidikan/Ilmu', 'Pendidikan/Ilmu'), ('Hiburan', 'Hiburan'), ('Kesehatan', 'Kesehatan'), ('Kebersihan', 'Kebersihan'), ('Belanja', 'Belanja'), ('Darurat', 'Darurat'), ('Tempat tinggal', 'Tempat tinggal'), ('Produktivitas', 'Produktivitas'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField()),
                ('prioritas', models.CharField(choices=[('Butuh', 'Butuh'), ('Harus', 'Harus'), ('Ingin', 'Ingin')], max_length=10)),
                ('dompet', models.CharField(choices=[('Cash', 'Cash'), ('OVO', 'OVO'), ('BJB', 'BJB'), ('Livin', 'Livin'), ('ShopeePay', 'ShopeePay'), ('Lainnya', 'Lainnya')], max_length=10)),
            ],
        ),
    ]
